export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CHATS = "GET_CHATS";
export const AFTER_POST_MESSAGE = "AFTER_POST_MESSAGE";
